# Python Funscript Editor hyperparameter config

###########
# General #
###########

# Specify the minimum required frames for the tracking. Wee need this parameter to
# ensure there is at least two strokes in the tracking result.
min_frames: 90

# reaction time of the user to stop the tracking when scene changed or tracking box shifts
user_reaction_time_in_milliseconds: 800


# Signal Processing Hyperparameter
signal:
  # Specify the window size for the calculation of the reference value for the local min and max search.
  avg_sec_for_local_min_max_extraction: 2.0

  # min interframes without an additional datapoint for the evenly intermediate algorithm
  min_evenly_intermediate_interframes: 2


# Scene Detector Hyperparameter
scene_detector:
  # Specify the minimum scene length in seconds
  min_scene_len_in_seconds: 3

  # Threshold value for the content detector to detect an scene change
  scene_content_detector_threshold: 30.0

  # Threshold value for the threshold detector to detect an scene change
  scene_threshold_detector_threshold: 12


# Tracker Hyperparameter
tracker:
  # Specify the init phase for the tracker (currently only used for the plausible check)
  tracking_init_phase_in_sec: 6

  # plausiblity factor to veriify a correct tracking position
  tracking_plausibility_factor_x: 4.0

  # plausiblity factor to veriify a correct tracking position
  tracking_plausibility_factor_y: 2.5

